#!/usr/bin/env python3
"""
Corrected HTTP-Based Intake Sync for TankID
Fixes:
1. R2 upload paths to /documents/[uuid]/[document_name]
2. Proper facility number separation (client_facility_number vs state_facility_number vs UUID)
"""

import json
import requests
import argparse
from datetime import datetime
import logging
import os
import base64
import uuid

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s:%(name)s:%(message)s')
logger = logging.getLogger(__name__)

class CorrectedHTTPIntakeSyncManager:
    def __init__(self, api_url="https://tankid-api.fly.dev", dry_run=False):
        self.api_url = api_url.rstrip('/')
        self.dry_run = dry_run
        self.sync_endpoint = f"{self.api_url}/api/intake-sync"
        
        # Load document UUID to file path mapping
        self.doc_mapping = {}
        self.load_document_mapping()
    
    def load_document_mapping(self):
        """Load document UUID to file path mapping from documents.json"""
        try:
            with open('mock_data/documents.json', 'r') as f:
                documents = json.load(f)
            
            for doc in documents:
                if 'id' in doc and 'storage_path' in doc:
                    # Map UUID to actual file path
                    storage_path = doc['storage_path']
                    # Convert local:// protocol to actual path
                    if storage_path.startswith('local://storage/'):
                        actual_path = storage_path.replace('local://storage/', 'local_storage/')
                        self.doc_mapping[doc['id']] = {
                            'file_path': actual_path,
                            'original_filename': os.path.basename(doc.get('file_path', actual_path))
                        }
                        logger.info(f"📋 Mapped {doc['id'][:8]}... → {os.path.basename(actual_path)}")
            
            logger.info(f"📚 Loaded {len(self.doc_mapping)} document mappings")
        except Exception as e:
            logger.error(f"❌ Error loading document mapping: {e}")
    
    def parse_facility_number_from_address(self, address):
        """Extract facility number from address like '1005 Industrial Parkway'"""
        try:
            if address and address.strip():
                # Split address and try to get first part as number
                parts = address.strip().split()
                if parts and parts[0].isdigit():
                    return int(parts[0])
        except:
            pass
        return None
    
    def parse_facility_number_from_name(self, facility_name):
        """Extract facility number from facility name or other sources"""
        # Try to extract number from facility name if it contains digits
        try:
            if facility_name:
                import re
                numbers = re.findall(r'\b\d+\b', facility_name)
                if numbers:
                    return int(numbers[-1])  # Use last number found
        except:
            pass
        return None
    
    def normalize_facility_data(self, tank_data):
        """Fix facility naming/numbering issues"""
        # Extract client_facility_number from address or name
        facility_address = tank_data.get('facility_address', '')
        facility_name = tank_data.get('facility_name', '')
        
        # Try to get facility number from address first
        client_facility_number = self.parse_facility_number_from_address(facility_address)
        
        # If not found in address, try facility name
        if not client_facility_number:
            client_facility_number = self.parse_facility_number_from_name(facility_name)
        
        # Default to 1005 if we can't parse it (based on recent example)
        if not client_facility_number:
            logger.warning(f"⚠️ Could not parse facility number from '{facility_address}' or '{facility_name}', defaulting to 1005")
            client_facility_number = 1005
        
        # Create corrected facility data
        corrected_data = tank_data.copy()
        
        # Fix facility numbering
        corrected_data['client_facility_number'] = client_facility_number
        corrected_data['state_facility_number'] = client_facility_number  # Same unless specified otherwise
        
        # Remove the incorrect facility_uuid (will be auto-generated by production DB)
        if 'facility_uuid' in corrected_data:
            logger.info(f"🔧 Removing incorrect facility_uuid: {corrected_data['facility_uuid']}")
            del corrected_data['facility_uuid']
        
        # Log the corrections
        logger.info(f"🔧 Normalized facility: {facility_name} → client_facility_number={client_facility_number}, state_facility_number={client_facility_number}")
        
        return corrected_data
    
    def read_file_as_base64(self, file_path_or_uuid):
        """Read local file and convert to base64, handling UUID mapping"""
        try:
            # Check if this is a UUID that needs mapping
            if file_path_or_uuid in self.doc_mapping:
                mapping = self.doc_mapping[file_path_or_uuid]
                actual_path = mapping['file_path']
                original_filename = mapping['original_filename']
                logger.info(f"📄 Mapping UUID {file_path_or_uuid[:8]}... → {original_filename}")
            else:
                # Direct file path
                actual_path = file_path_or_uuid
                if actual_path.startswith('local://storage/'):
                    actual_path = actual_path.replace('local://storage/', 'local_storage/')
                original_filename = os.path.basename(actual_path)
            
            if os.path.exists(actual_path):
                with open(actual_path, 'rb') as f:
                    file_content = f.read()
                    return base64.b64encode(file_content).decode('utf-8'), original_filename
            else:
                logger.error(f"❌ File not found: {actual_path}")
                return None, None
        except Exception as e:
            logger.error(f"❌ Error reading file {file_path_or_uuid}: {e}")
            return None, None
    
    def load_local_data(self):
        """Load tanks with corrected facility data and proper R2 document paths"""
        try:
            with open('mock_data/tanks.json', 'r') as f:
                tanks = json.load(f)
            
            # Process each tank
            for i, tank in enumerate(tanks):
                # First, fix facility naming/numbering issues
                tanks[i] = self.normalize_facility_data(tank)
                
                # Then process documents with correct R2 paths
                if 'document_ids' in tanks[i]:
                    tank_documents = []
                    for doc_uuid in tanks[i]['document_ids']:
                        base64_content, filename = self.read_file_as_base64(doc_uuid)
                        if base64_content and filename:
                            # Create corrected R2 path: /documents/[uuid]/[document_name]
                            r2_path = f"/documents/{doc_uuid}/{filename}"
                            
                            tank_documents.append({
                                'filename': filename,
                                'content': base64_content,
                                'document_uuid': doc_uuid,
                                'r2_path': r2_path,  # Correct R2 destination path
                                'file_size': len(base64.b64decode(base64_content)),
                                'mime_type': 'application/pdf'
                            })
                            logger.info(f"✅ Document: {filename} → R2 path: {r2_path}")
                        else:
                            logger.warning(f"⚠️ Skipping missing file for UUID: {doc_uuid}")
                    
                    tanks[i]['documents_content'] = tank_documents
                    logger.info(f"🏗️ Tank {tanks[i]['serial_number']}: {len(tank_documents)} documents with corrected R2 paths")
            
            logger.info(f"📊 Loaded {len(tanks)} tanks with corrected facility data and R2 paths")
            return tanks
        
        except FileNotFoundError as e:
            logger.error(f"❌ Data file not found: {e}")
            return []
        except json.JSONDecodeError as e:
            logger.error(f"❌ Invalid JSON in data files: {e}")
            return []
    
    def sync_to_production(self):
        """Sync corrected data to production via HTTP API"""
        tanks = self.load_local_data()
        
        if not tanks:
            logger.info("📭 No tanks to sync")
            return {"success": True, "message": "No data to sync"}
        
        # Prepare payload with corrected data
        payload = {
            "tanks": tanks,
            "sync_timestamp": datetime.now().isoformat(),
            "dry_run": self.dry_run,
            "corrections": {
                "r2_paths": "Fixed to /documents/[uuid]/[filename] format",
                "facility_numbers": "Added client_facility_number and state_facility_number fields",
                "facility_uuids": "Removed incorrect facility_uuid (will be auto-generated by DB)"
            }
        }
        
        # Count documents
        total_documents = sum(len(tank.get('documents_content', [])) for tank in tanks)
        logger.info(f"🚀 Syncing CORRECTED data to {self.sync_endpoint}")
        logger.info(f"📦 Payload: {len(tanks)} tanks, {total_documents} documents with corrected R2 paths")
        
        if self.dry_run:
            logger.info("🧪 DRY RUN - Showing corrected payload structure:")
            # Show first tank as example
            if tanks:
                example_tank = tanks[0]
                logger.info(f"📋 Example tank: {example_tank['serial_number']}")
                logger.info(f"   - client_facility_number: {example_tank.get('client_facility_number')}")
                logger.info(f"   - state_facility_number: {example_tank.get('state_facility_number')}")
                logger.info(f"   - facility_name: {example_tank.get('facility_name')}")
                if example_tank.get('documents_content'):
                    doc = example_tank['documents_content'][0]
                    logger.info(f"   - Example R2 path: {doc['r2_path']}")
            return {"success": True, "message": "Dry run completed with corrected data"}
        
        try:
            response = requests.post(
                self.sync_endpoint,
                json=payload,
                headers={'Content-Type': 'application/json'},
                timeout=300  # 5 minute timeout for large uploads
            )
            
            if response.status_code == 200:
                result = response.json()
                logger.info("✅ CORRECTED sync completed successfully!")
                logger.info(f"📊 Results: {result}")
                return result
            else:
                logger.error(f"❌ Sync failed with status {response.status_code}")
                logger.error(f"📄 Response: {response.text}")
                return {"success": False, "error": f"HTTP {response.status_code}: {response.text}"}
        
        except requests.exceptions.RequestException as e:
            logger.error(f"❌ HTTP request failed: {e}")
            return {"success": False, "error": str(e)}
        except Exception as e:
            logger.error(f"❌ Sync failed: {e}")
            return {"success": False, "error": str(e)}

def main():
    parser = argparse.ArgumentParser(description='Corrected HTTP-based TankID intake sync')
    parser.add_argument('--dry-run', action='store_true', 
                       help='Test sync without making actual changes (shows corrected data structure)')
    parser.add_argument('--api-url', default='https://tankid-api.fly.dev',
                       help='TankID API base URL')
    
    args = parser.parse_args()
    
    print("🔧 TankID CORRECTED Intake Sync")
    print(f"🚀 API: {args.api_url}")
    print(f"🧪 Dry Run: {args.dry_run}")
    print("📝 Fixes: R2 paths + facility numbering")
    print("-" * 50)
    
    sync_manager = CorrectedHTTPIntakeSyncManager(
        api_url=args.api_url,
        dry_run=args.dry_run
    )
    
    result = sync_manager.sync_to_production()
    
    if result.get('success'):
        print("\n✅ Sync completed successfully!")
        if not args.dry_run:
            print("📊 Check production database for updated data with corrected facility numbers")
            print("📄 Documents uploaded to corrected R2 paths: /documents/[uuid]/[filename]")
    else:
        print(f"\n❌ Sync failed: {result.get('error')}")
        exit(1)

if __name__ == "__main__":
    main()